apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  # namespace: test
  timeouts:
    apply: 420s
    assert: 420s
    cleanup: 240s
    delete: 240s
    error: 200s
    exec: 200s
  skipDelete: false
  failFast: true
